const nbaTeamMap = {
    'Atlanta Hawks': 'Hawks',
    'Boston Celtics': 'Celtics',
    'Brooklyn Nets': 'Nets',
    'Charlotte Hornets': 'Hornets',
    'Chicago Bulls': 'Bulls',
    'Cleveland Cavaliers': 'Cavaliers',
    'Dallas Mavericks': 'Mavericks',
    'Denver Nuggets': 'Nuggets',
    'Detroit Pistons': 'Pistons',
    'Golden State Warriors': 'Warriors',
    'Houston Rockets': 'Rockets',
    'Indiana Pacers': 'Pacers',
    'Los Angeles Clippers': 'Clippers',
    'Los Angeles Lakers': 'Lakers',
    'Memphis Grizzlies': 'Grizzlies',
    'Miami Heat': 'Heat',
    'Milwaukee Bucks': 'Bucks',
    'Minnesota Timberwolves': 'Timberwolves',
    'New Orleans Pelicans': 'Pelicans',
    'New York Knicks': 'Knicks',
    'Oklahoma City Thunder': 'Thunder',
    'Orlando Magic': 'Magic',
    'Philadelphia 76ers': '76ers',
    'Phoenix Suns': 'Suns',
    'Portland Trail Blazers': 'Trail Blazers',
    'Sacramento Kings': 'Kings',
    'San Antonio Spurs': 'Spurs',
    'Toronto Raptors': 'Raptors',
    'Utah Jazz': 'Jazz',
    'Washington Wizards': 'Wizards'
};
const nhlTeamMap = {'Anaheim Ducks': 'Ducks',
    'Boston Bruins': 'Bruins',
    'Buffalo Sabres': 'Sabres',
    'Calgary Flames': 'Flames',
    'Carolina Hurricanes': 'Hurricanes',
    'Chicago Blackhawks': 'Blackhawks',
    'Colorado Avalanche': 'Avalanche',
    'Columbus Blue Jackets': 'Blue Jackets',
    'Dallas Stars': 'Stars',
    'Detroit Red Wings': 'Red Wings',
    'Edmonton Oilers': 'Oilers',
    'Florida Panthers': 'Panthers',
    'Los Angeles Kings': 'Kings',
    'Minnesota Wild': 'Wild',
    'Montreal Canadiens': 'Canadiens',
    'Montréal Canadiens': 'Canadiens',
    'Nashville Predators': 'Predators',
    'New Jersey Devils': 'Devils',
    'New York Islanders': 'Islanders',
    'New York Rangers': 'Rangers',
    'Ottawa Senators': 'Senators',
    'Philadelphia Flyers': 'Flyers',
    'Pittsburgh Penguins': 'Penguins',
    'San Jose Sharks': 'Sharks',
    'Seattle Kraken': 'Kraken',
    'St Louis Blues': 'Blues',
    'St. Louis Blues': 'Blues',
    'Tampa Bay Lightning': 'Lightning',
    'Toronto Maple Leafs': 'Maple Leafs',
    'Utah Hockey Club': 'Utah',
    'Vancouver Canucks': 'Canucks',
    'Vegas Golden Knights': 'Golden Knights',
    'Washington Capitals': 'Capitals',
    'Winnipeg Jets': 'Jets'
  };

  const mlbTeamMap = { 'Arizona Diamondbacks': 'Diamondbacks',
    'Atlanta Braves': 'Braves',
    'Baltimore Orioles': 'Orioles',
    'Boston Red Sox': 'Red Sox',
    'Chicago White Sox': 'White Sox',
    'Chicago Cubs': 'Cubs',
    'Cincinnati Reds': 'Reds',
    'Cleveland Guardians': 'Guardians',
    'Colorado Rockies': 'Rockies',
    'Detroit Tigers': 'Tigers',
    'Houston Astros': 'Astros',
    'Kansas City Royals': 'Royals',
    'Los Angeles Angels': 'Angels',
    'Los Angeles Dodgers': 'Dodgers',
    'Miami Marlins': 'Marlins',
    'Milwaukee Brewers': 'Brewers',
    'Minnesota Twins': 'Twins',
    'New York Mets': 'Mets',
    'New York Yankees': 'Yankees',
    'Oakland Athletics': 'Athletics',
    'Philadelphia Phillies': 'Phillies',
    'Pittsburgh Pirates': 'Pirates',
    'San Diego Padres': 'Padres',
    'San Francisco Giants': 'Giants',
    'Seattle Mariners': 'Mariners',
    'St Louis Cardinals': 'Cardinals',
    'St. Louis Cardinals': 'Cardinals',
    'Tampa Bay Rays': 'Rays',
    'Texas Rangers': 'Rangers',
    'Toronto Blue Jays': 'Blue Jays',
    'Washington Nationals': 'Nationals',
  }
  
function getMascotFromFullName(teamName) {
return nbaTeamMap[teamName] || nhlTeamMap[teamName] || mlbTeamMap[teamName] || teamName;
}

module.exports = { getMascotFromFullName };