name: Deploy Auth Service to Cloud Run

on:
  push:
    paths:
      - 'services/auth-service/**'
      - '.github/workflows/deploy-auth-service.yml'
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Auth Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch complete history
  
      - name: Setup timestamp for unique build
        run: |
          echo "BUILD_TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
          echo "Deploying build: ${{ env.BUILD_TIMESTAMP }}"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Create .dockerignore file
        working-directory: ./services/auth-service
        run: |
          echo "node_modules" > .dockerignore
          echo ".git" >> .dockerignore
          echo ".env" >> .dockerignore
          echo "npm-debug.log" >> .dockerignore

      - name: Debug - List files to be included in build
        run: |
          echo "Files in auth-service directory:"
          find services/auth-service -type f | grep -v "node_modules" | sort

      - name: Build and push Docker image
        id: build_image
        run: |
          # Define version info
          COMMIT_SHA="${{ github.sha }}"
          IMAGE_TAG="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sportsbook-repo/auth-service:${COMMIT_SHA}"

          echo "Building image: $IMAGE_TAG"
          
          # Build from the auth-service directory
          cd services/auth-service
          
          # Build with no cache and pass commit SHA
          docker build --no-cache \
            --build-arg BUILD_TIMESTAMP="${{ env.BUILD_TIMESTAMP }}" \
            --build-arg COMMIT_SHA="${{ github.sha }}" \
            -t "${IMAGE_TAG}" .
          
          echo "Pushing image: $IMAGE_TAG"
          docker push ${IMAGE_TAG}
          
          # Store image tag in environment variable for next steps
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV



      - name: Debug deployed image name
        run: |
          echo "DEBUG - Value from steps.build_image.outputs.image_tag_output: '${{ steps.build_image.outputs.image_tag_output }}'"
  

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying image: $IMAGE_TAG"
          
          DEPLOY_TIMESTAMP=$(date +%Y%m%d%H%M%S)

          gcloud run deploy auth-service \
            --image="$IMAGE_TAG" \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=sportsbook-simulation:us-central1:sportsbook-instance \
            --set-env-vars=JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --set-env-vars=DB_HOST=${{ secrets.DB_HOST }} \
            --set-env-vars=DB_NAME=sportsbook_db \
            --set-env-vars=DB_USER=sportsbook_user \
            --set-env-vars=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --set-env-vars=DB_INSTANCE_CONNECTION_NAME=sportsbook-simulation:us-central1:sportsbook-instance \
            --set-env-vars="BUILD_ID=${DEPLOY_TIMESTAMP}" \
            --set-env-vars="COMMIT_SHA=${{ github.sha }}" \
            --service-account=github-actions-deployer@sportsbook-simulation.iam.gserviceaccount.com
            --update-traffic

      - name: Verify traffic routing
        run: |
          echo "Verifying traffic routing to new revision..."
          gcloud run services describe auth-service \
            --platform=managed \
            --region=us-central1 \
            --format="yaml(status.traffic, status.latestCreatedRevisionName, status.latestReadyRevisionName)"