name: Deploy Betting Service to Cloud Run

on:
  push:
    paths:
      - 'services/betting-service/**'
      - '.github/workflows/deploy-betting-service.yml'
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Betting Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sportsbook-repo/betting-service ./services/betting-service
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sportsbook-repo/betting-service

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy betting-service \
            --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sportsbook-repo/betting-service \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=\
            BETTING_PORT=${{ secrets.BETTING_PORT }},\
            JWT_SECRET=${{ secrets.JWT_SECRET }},\
            DB_HOST=${{ secrets.DB_HOST }},\
            DB_NAME=${{ secrets.DB_NAME }},\
            DB_USER=${{ secrets.DB_USER }},\
            DB_PASSWORD=${{ secrets.DB_PASSWORD }},\
            DB_PORT=${{ secrets.DB_PORT }},\
            ODDS_API_KEY=${{ secrets.ODDS_API_KEY }},\
            ODDS_API_NBA_ODDS_URL=${{ secrets.ODDS_API_NBA_ODDS_URL }},\
            ODDS_API_NHL_ODDS_URL=${{ secrets.ODDS_API_NHL_ODDS_URL }},\
            ODDS_API_MLB_ODDS_URL=${{ secrets.ODDS_API_MLB_ODDS_URL }},\
            ESPN_API_NBA_SCOREBOARD=${{ secrets.ESPN_API_NBA_SCOREBOARD }},\
            ESPN_API_NHL_SCOREBOARD=${{ secrets.ESPN_API_NHL_SCOREBOARD }},\
            ESPN_API_MLB_SCOREBOARD=${{ secrets.ESPN_API_MLB_SCOREBOARD }},\
